version: '3.8'
services:
  dev-db:
    image: mysql:8.0.32
    ports:
      - 5434:5432
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123
      MYSQL_DB: nest
    networks:
      - freecodecamp
  test-db:
    image: mysql:8.0.32
    ports:
      - 5435:5432
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123
      MYSQL_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
