version: '3.8'
services:
  dev-db:
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - freecodecamp
  test-db:
    image: mysql:8.0.32
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - freecodecamp
networks:
  freecodecamp:
