name: e2e-test-server

on:
  pull_request:
    paths:
      - "server/**"

env:
  DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5433
  JWT_SECRET: secret

jobs:
  e2e-test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Run e2e tests
        working-directory: ./server
        run: |
          npm i
          npm run test:ci
