name: e2e-server-testing

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup server directory
        working-directory: ./server
      - name: Install packages
        run: npm i
      - name: Run e2e tests
        run: npm run test:ci
