name: e2e-test-server

on:
  pull_request:
    paths:
      - "server/**"

env:
  DATABASE_URL: ${{vars.DATABASE_URL}}
  JWT_SECRET: ${{vars.JWT_SECRET}}

jobs:
  e2e-test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Run e2e tests
        working-directory: ./server
        env:
          DATABASE_URL: ${{vars.DATABASE_URL}}
          JWT_SECRET: ${{vars.JWT_SECRET}}
        run: |
          npm i
          echo "overridden variable : ${{ vars.DATABASE_URL }}"
          npm run test:ci
