name: e2e-server-testing

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run e2e tests
        working-directory: ./server
        run: |
          npm i
          npm run test:ci
