name: e2e-server-testing

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test envs
        run: |
          echo ${{ vars.DATABASE_URL }} | sed 's/./& /g' 
          echo ${{ vars.JWT_SECRET }} | sed 's/./& /g'
      - name: Run e2e tests
        working-directory: ./server
        run: |
          npm i
          npm run test:ci
        env:
          DATABASE_URL: ${{vars.DATABASE_URL}}
          JWT_SECRET: ${{vars.JWT_SECRET}}
