name: e2e-server-testing

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          DATABASE_URL: ${{env.DATABASE_URL}}
          JWT_SECRET: ${{env.JWT_SECRET}}
      - name: Run e2e tests
        run: |
          npm i
          npm run test:ci
